[package]
name = "interface_tf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = { version = "0.19.0", features = ["eager"] }
thirtyfour_sync = { version = "0.27.1" }
image = "0.24.3"
reqwest = { version = "0.11", features = ["blocking"] }
opencv = "0.66.0"
