[package]
name = "interface_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# show-image = { version = "0.12.3", dev = true }
opencv = "0.66.0"
